### ISSUE TITLE
metaresearch software engineers: MRSE vs RSE, perhaps?

### ISSUE THREAD

**Issue by softloud** [softloud/codeproof#2]
I'm currently writing another paper about research engineering practices and need precise terminology.  

I really appreciate Katz and McHenry taking the time to discuss the idea of a [super research software engineer](https://danielskatzblog.wordpress.com/) (Super RSE), as an augmentation of the "traditional" RSE role. 

Rather than _Super_, what about meta? So, we then have research software engineers, and **metaresearch software engineers**? I, myself, am on the fence about MRSE vs MSE.

I like _meta_ better than super, because, as the authors note, we do not wish to imply that other researchers are not super.  

> We hope that this concept of Super RSEs will be useful in setting the boundaries of RSEs and perhaps in defining a portion of the RSE space. And we recognize that Super RSEs might not be the final term for this kind of work, as it might be seen as implying that other parts of the RSE space are less super, which is not our intention.

**Comment by softloud** [comment]
Thoughts, @benmarwick, @noamross, @ekothe, @lingtax, @alexpghayes?

**Comment by rowlandm** [comment]
Hmmm. I'm not sure about super or meta. Actually, re-reading his blog post I'm not sure of his definition either....

Actually, we never really clarified and defined the idea of a "traditional" RSE did we?

If you look at the front page of the AU/NZ website:

If you are 1. an academic/researcher who codes but are lacking recognition and metrics needed to progress your academic career; 2. a 'generalist' who brings communities together and can engage with both researchers and technical staff; 3. a professional software engineer working in the research space; or 4. a system administrator who maintains research systems, you should think about joining. 

Maybe he is talking about 3. professional software engineers working on software infrastructure that the others use to make things easier for them.

The pitch I make to the University I work in is that we need a software infrastructure ecosystem that is backed by the community to make it easier to build new projects from scratch, and also make it easier to maintain in a production environment in the future by professional sysadmins. The people who build that community and build that software infrastructure might be the ones you are defining?

**Comment by danielskatz** [comment]
Don't take the name too seriously - we're more interested in expressing that there are a bunch of things that fall under research software engineering - not just an RSE who works with a faculty member to develop their software.

**Comment by noamross** [comment]
There's a parallel to some degree with researchers who spend a lot of effort on "meta-research" (often categorized with "service"). "Meta-research" might be work in field-wide standards, publication and  editorial work, other social infrastructure like society administration, etc. I'm not sure a separate categorization is important, though recognizing the spectrum of tasks in tasks probably is.  Most researchers do some of both but the balance varies quite a bit.  For most RSEs, especially if one works in an open-source context, one's work can easily slide back and forth - e.g., implementing a method for your own use and wrapping it up as a reusable package.

**Comment by alexpghayes** [comment]
My impression is that RSE is a rather broad field and that this in general a hard conversation to have without breaking RSE down into sub-fields, much as is currently happening with data science. [Here's an interesting article](https://www.linkedin.com/pulse/one-data-science-job-doesnt-fit-all-elena-grewal/) on AirBnB making these differentiations.

**Comment by softloud** [comment]
Really appreciate the discussion; I'm presenting this paper tomorrow and this really helped me figure out what I think is important to highlight. That is, why I've been considering the terminology. A rose by any other name and all that, but I think @noamross nailed it; I wish to highlight the role of metaresearch in rse work. 

![image](https://user-images.githubusercontent.com/13408706/61683002-38e80300-ad57-11e9-88f7-2e20f0508830.png)
